const IS_OVERVIEW_DATA_LOADING = "IS_OVERVIEW_DATA_LOADING";
const IS_SEARCH_DATA_LOADING = "IS_SEARCH_DATA_LOADING";
const FETCH_GLOBAL_QUOTE_FAILED = "FETCH_GLOBAL_QUOTE_FAILED";
const FETCH_GLOBAL_QUOTE_SUCCESSFULLY = "FETCH_GLOBAL_QUOTE_SUCCESSFULLY";
const FETCH_OVERVIEW_DATA_SUCCESSFULLY = "FETCH_OVERVIEW_DATA_SUCCESSFULLY";
const FETCH_OVERVIEW_DATA_FAILED = "FETCH_OVERVIEW_DATA_FAILED";
const FETCH_SEARCH_ENDPOINT_DATA = "FETCH_SEARCH_ENDPOINT_DATA";
const FETCH_TIME_SERIES_DAILY_ADJUSTED_SUCCESSFULLY =
  "FETCH_TIME_SERIES_DAILY_ADJUSTED_SUCCESSFULLY";
const FETCH_TIME_SERIES_DAILY_ADJUSTED_FAILED = "FETCH_TIME_SERIES_DAILY_ADJUSTED_FAILED";
const RESET_GLOBAL_QUOTE = "RESET_GLOBAL_QUOTE";

const types = {
  FETCH_TIME_SERIES_DAILY_ADJUSTED_SUCCESSFULLY,
  FETCH_TIME_SERIES_DAILY_ADJUSTED_FAILED,
  FETCH_SEARCH_ENDPOINT_DATA,
  IS_SEARCH_DATA_LOADING,
  FETCH_OVERVIEW_DATA_SUCCESSFULLY,
  FETCH_OVERVIEW_DATA_FAILED,
  FETCH_GLOBAL_QUOTE_FAILED,
  FETCH_GLOBAL_QUOTE_SUCCESSFULLY,
  RESET_GLOBAL_QUOTE,
  IS_OVERVIEW_DATA_LOADING,
};
export default types;
