const FETCH_INTRADAY_DATA_SUCCESSFULLY = "FETCH_INTRADAY_DATA_SUCCESSFULLY";
const FETCH_INTRADAY_DATA_FAILED = "FETCH_INTRADAY_DATA_FAILED";
const FETCH_SEARCH_ENDPOINT_DATA = "FETCH_SEARCH_ENDPOINT_DATA";
const IS_SEARCH_DATA_LOADING = "IS_SEARCH_DATA_LOADING";

const types = {
  FETCH_INTRADAY_DATA_SUCCESSFULLY,
  FETCH_INTRADAY_DATA_FAILED,
  FETCH_SEARCH_ENDPOINT_DATA,
  IS_SEARCH_DATA_LOADING,
};
export default types;
